export { default as ArrowIcon } from './ArrowIcon';
export { default as BellIcon } from './BellIcon';
export { default as CloseEyeIcon } from './CloseEyeIcon';
export { default as MenuIcon } from './MenuIcon';
export { default as OpenEyeIcon } from './OpenEyeIcon';
export { default as PlusIcon } from './PlusIcon';
export { default as CalenderIcon } from './Sidebar Icons/CalenderIcon';
export { default as ExamIcon } from './Sidebar Icons/ExamIcon';
export { default as HomeIcon } from './Sidebar Icons/HomeIcon';
export { default as LogoutIcon } from './Sidebar Icons/LogoutIcon';
export { default as ResultIcon } from './Sidebar Icons/ResultIcon';
export { default as SchoolIcon } from './Sidebar Icons/SchoolIcon';
export { default as FacebookIcon } from './Social Icons/FacebookIcon';
export { default as GithubIcon } from './Social Icons/GithubIcon';
export { default as InstagramIcon } from './Social Icons/InstagramIcon';
export { default as LinkedInIcon } from './Social Icons/LinkedInIcon';
export { default as TwitterIcon } from './Social Icons/TwitterIcon';
